f<-read.csv("C:\\Users\\Shubham\\Downloads\\Documents\\Data Science\\Assignment Question\\Basic Statastics Level 1\\Cars.csv")
library(nortest)
a<-mean(f$MPG)
b<-median(f$MPG)
c<-sd(f$MPG)
qqnorm(f$MPG)
qqline(f$MPG)
library(moments)
skewness(f$MPG)
kurtosis(f$MPG)
hist(f$MPG)
